name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH setup
        run: |
          ls -la
          ssh -T ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} || true

      - name: Copy files to the server
        run:
          scp -r forex_trading_algo ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:~/forex_algo/forex_trading_algo

      - name: Restart the application
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'chmod -R 777 ~/forex_algo'
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'cd ~/forex_algo/forex_trading_algo; python3 trade_eurusd.py;'
